# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      
  workflow_dispatch:
    inputs:
      browserName:
        description: 'Browser type'
        required: false
        type: string
        default: 'chrome'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip
        sudo apt-get install -y google-chrome-stable
        
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | sed 's/\.[0-9]*$//')
        LATEST_CHROMEDRIVER=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
        wget https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Start Xvfb
      run: |
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1280x1024x24 &

    - name: Build with Maven
      id: build
      run: mvn clean
      
    - name: Run tests
      if: steps.build.outcome == 'success'
      run: mvn -DbrowserName=${{ inputs.browserName || 'CHROME' }} verify

    - name: Get Allure history
      uses: actions/checkout@v3
      if: steps.build.outcome == 'success'
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure report action
      uses: simple-elf/allure-report-action@master
      if: steps.build.outcome == 'success'
      id: allure-report
      with:
        allure_results: ${{ vars.ALLURE_RESULTS_PATH }}
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: allure-history
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
